### ISSUE TITLE
Exporting text columns

### ISSUE THREAD

**Issue by lnicole08** [OpenSourcePhysics/tracker#48]
Hello, I am trying to export my text column that Ive annotated manually every frame on the behavior of a certain sample. However it seems that the software is unable to export it? When I click export, all the column options show up except text column. Please kindly advise! Thank you

**Comment by dobrown** [comment]
Yes, I see the issue and that is a bug we must fix. However, in the
meantime you can copy the text column to the clipboard by selecting it in a
data table, right-clicking and choosing Copy Selected Cells (either as
formatted or full precision).

**Comment by dobrown** [comment]
This issue has been fixed. If you want I can send you the tracker.jar, I
just need your email address.  Doug
