### ISSUE TITLE
osp-tracker 6.1.6 installation failed on osx

### ISSUE THREAD

**Issue by chenrui333** [OpenSourcePhysics/tracker#52]
👋 trying to update cask to the latest release, but found some installation issue

```
==> Purging files for version 6.1.6 of Cask osp-tracker
Error: Failure while executing; `/usr/bin/sudo -E PATH=/usr/local/bin:/usr/local/sbin:/usr/local/Homebrew/Library/Homebrew/shims/shared:/usr/bin:/bin:/usr/sbin:/sbin -- /usr/local/Caskroom/osp-tracker/6.1.6/Tracker-6.1.6-osx-installer.app/Contents/MacOS/installbuilder.sh --mode unattended` exited with 1. Here's the output:
Problem running post-install step. Installation may not complete correctly
 No origin file found that matched /usr/local/tracker/Tracker.app/Contents/Java/tracker-6.1.6.jar
```
I can reproduce in my local machine as well

<img width="671" alt="image" src="https://github.com/OpenSourcePhysics/tracker/assets/1580956/c3d5d9a9-65db-440d-8311-d9cea65d67a3">

---

relates to https://github.com/Homebrew/homebrew-cask/pull/164873

**Comment by dobrown** [comment]
Thanks for your bug report. I found and fixed the problem and there should
be a new installer on the Tracker website by the end of the day (Jan 20).
